// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiyhRWLutSJ58PleEQr1IhIrdLVowJ-fw',
    appId: '1:74932961017:web:7f41de27915fd1adb86c28',
    messagingSenderId: '74932961017',
    projectId: 'todo-list-cdec3',
    authDomain: 'todo-list-cdec3.firebaseapp.com',
    storageBucket: 'todo-list-cdec3.firebasestorage.app',
    measurementId: 'G-RFGR81KF25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp76YDNp814mj_VuVUeX-Z0CAxvLXRt1Q',
    appId: '1:74932961017:android:f26cb5d0a5d5d3ddb86c28',
    messagingSenderId: '74932961017',
    projectId: 'todo-list-cdec3',
    storageBucket: 'todo-list-cdec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEe6YwkZUFABc3gUWtiOUpLnDO5UXurRM',
    appId: '1:74932961017:ios:ab4e200cea6fb44cb86c28',
    messagingSenderId: '74932961017',
    projectId: 'todo-list-cdec3',
    storageBucket: 'todo-list-cdec3.firebasestorage.app',
    iosBundleId: 'com.example.todoooo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEe6YwkZUFABc3gUWtiOUpLnDO5UXurRM',
    appId: '1:74932961017:ios:ab4e200cea6fb44cb86c28',
    messagingSenderId: '74932961017',
    projectId: 'todo-list-cdec3',
    storageBucket: 'todo-list-cdec3.firebasestorage.app',
    iosBundleId: 'com.example.todoooo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiyhRWLutSJ58PleEQr1IhIrdLVowJ-fw',
    appId: '1:74932961017:web:ea2cfbc665ac4df3b86c28',
    messagingSenderId: '74932961017',
    projectId: 'todo-list-cdec3',
    authDomain: 'todo-list-cdec3.firebaseapp.com',
    storageBucket: 'todo-list-cdec3.firebasestorage.app',
    measurementId: 'G-SQ5NMHBT5G',
  );
}
